# Generated by Django 3.2.16 on 2022-12-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('accounts', '0003_profile_hired_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hired_cars',
            field=models.ManyToManyField(blank=True, to='vehicles.Car'),
        ),
    ]
