# Generated by Django 3.2.16 on 2022-12-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30, unique=True)),
                ('staff_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutoPark',
            fields=[
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='branches.companybranch')),
                ('parking_capacity', models.PositiveIntegerField()),
                ('taken_spaces', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
