# Generated by Django 3.2.16 on 2022-12-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopark',
            name='taken_spaces',
        ),
    ]
