# Generated by Django 3.2.16 on 2022-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30, unique=True)),
                ('staff_capacity', models.PositiveIntegerField()),
                ('parking_capacity', models.PositiveIntegerField()),
                ('taken_parking_spaces', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
