# Generated by Django 3.2.16 on 2022-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=15)),
                ('expiry_date', models.DateField()),
                ('categories', models.TextField(max_length=2)),
            ],
        ),
    ]
