# Generated by Django 3.2.16 on 2022-12-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('accounts', '0004_alter_profile_hired_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.companybranch')),
                ('staff', models.ManyToManyField(blank=True, to='accounts.Profile')),
            ],
        ),
    ]
